title: c4d2hou
description: The documentation of the best C4D to Houdini Bridge

# Use GitHub Pages supported theme
theme: cayman

# Site configuration
url: https://lasselauch.github.io
baseurl: "/c4d2hou-docs"

# Repository info
github:
  repository_url: https://github.com/lasselauch/c4d2hou-docs
  is_project_page: true

# Navigation links
navigation_links:
  aescripts: https://aescripts.com/authors/f-l/lasse-lauch
  github: https://github.com/lasselauch/c4d2hou-docs

# Enable plugins (GitHub Pages supported only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache